### ISSUE TITLE
[NOT FUD] AND...

### ISSUE THREAD

**Issue by fSociety-Protected** [Byte4rray/Kill_Defender#1]
**First of all, NOT FUD.**
**_And anyways, WHY dont share the source??_**

**[PROOF]**
![sAAHUN22dHsL](https://user-images.githubusercontent.com/72263269/206047000-13992386-de4d-47ac-91f6-4e280abcd1c6.png)

**Comment by Byte4rray** [comment]
i uploaded the wrong file, please use kill_defenderV1.0.exe, thanks for your comment
proof
![kill_defenderV1 0](https://user-images.githubusercontent.com/119765421/207928806-91f9a603-bfcd-4ec7-bef3-4645b59fb394.png)

**Comment by fSociety-Protected** [comment]
_Yeah, but your version, **reboot** the machine._
_Thats why I want see the code, to see If I can **remove** this._

_Anyways, now dont care much, since I develop my own **Windows Defender Disabler**._

_And not only make unsuable Windows Defender, my program **disable the UAC**, **System Notifications**, Delete **logs**, Delete **Windows Backups** & Create inside Windows Defender a full **whole SYSTEM** to exclusion list. And ofc, tottally FULL **FUD**._  ᲼᲼<3_(^- ^*)

᲼᲼
**_### All made in C++_**
